name: Build & Release Flatpak

on:
  # Trigger only when pushing a tag like v1.0.0
  push:
    tags:
      - 'v*'

jobs:
  build-flatpak:
    # ► 1. Run only on Linux
    runs-on: ubuntu-latest

    # ► 2. Use a container pre-installed with Flatpak 23.08 runtime
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:23.08
      options: --privileged  # Required for flatpak-builder sandboxing

    steps:
      # 2.1 Check out the source code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2.2 Set up Temurin JDK 17 (required by Gradle & Compose Desktop)
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2.3 Set up Gradle and enable caching
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.12'

      # 2.4 Build Flatpak using your custom Gradle task
      - name: Build Flatpak bundle
        run: ./gradlew packageFlatpakReleaseDistributable

      # 2.5 Upload the generated .flatpak file as an artifact
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: build/flatpak/*.flatpak

  release:
    # ► 3. Publish the GitHub release with the Flatpak bundle
    needs: build-flatpak
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to upload release assets

    steps:
      # 3.1 Check out the source code (for tagging context)
      - name: Checkout source
        uses: actions/checkout@v4

      # 3.2 Download the Flatpak artifact built in the previous job
      - name: Download Flatpak artifact
        uses: actions/download-artifact@v4
        with:
          name: flatpak-bundle

      # 3.3 Create a GitHub release and attach the .flatpak file
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.flatpak"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
